
'use client'
// import type { Metadata } from "next";
// import { Providers } from "./providers";
// import { Rubik } from "next/font/google";
import { rubik } from "./ui/fonts"
import "./ui/globals.css";
import { Provider } from 'react-redux';
import store from './lib/store';
// const rubik = Rubik({
//   weight: ['300', '400', '500'],
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Frontend quiz",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <Provider store={store}>
          {children}
        </Provider>

      </body>
    </html>
  );
}

